### PR TITLE
[Feat] Dynamic Placeholder Substitution

### PR DESCRIPTION
**Pull request by VipinDevelops**
## Issue(s)

#16 

## Acceptance Criteria fulfillment

- [x]  Implemented placeholder identification and substitution for receiver-specific information
- [x]  Tested and validated the feature in different messaging scenarios.

## Proposed changes (including videos or screenshots)
[Screencast from 2024-08-16 19-57-27.webm](https://github.com/user-attachments/assets/28905a2c-8522-497f-bb66-78fa63145508)

### CODE REVIEW

**Comment by VipinDevelops** [comment]
Hey @hugocostadev  Please review this after the #15 PR. it's on top of it.

**Comment by VipinDevelops** [comment]
I've added additional features to our system, allowing us to dynamically retrieve and display the **username**, **name**, **email**, and **room** details. This functionality is now working across various platforms, including Channel, Private groups, Direct Message, and Live Chat.

**Comment by hugocostadev** [comment]
All good, just missing the README update! ;D

**Comment by VipinDevelops** [comment]
Sure I'll update those

**Comment by VipinDevelops** [comment]
image
Hey @hugocostadev  sorry for the delay I added the details about the dynamic value in the body placeholder and in README

**Pull request merged**
